### ISSUE TITLE
Add competitive coding problems or programs implementing algorithms in JAVA

### ISSUE THREAD

**Issue by raavikr12c** [raavikr12c/Popular-Algorithms-in-Java#1]
Add a PR with any competitive coding problem or with any program which implements popular algorithms (like backtracking, greedy, dnc, etc).

For competitive coding, in 
/Problems/ add competitive coding problems and solutions in the respective topic folder

Add a folder in /Problems/ with the Name of Problem Title.
Inside that folder add the solution ProblemTitle.java and a README.md
Make sure the class name is ProblemTitle that is the name of the file.
README.md must contain a detailed description of the problem.

**Comment by irohitsatya** [comment]
Can I add dynamic programming problem -- Longest Common Subsequence?

**Comment by raavikr12c** [comment]
> Can I add dynamic programming problem -- Longest Common Subsequence? @raavikr12c

ya sure.
